# Generated by Django 2.1 on 2020-04-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='type',
            new_name='problem',
        ),
    ]
