# Generated by Django 2.1 on 2020-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200420_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='if_compile',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='if_run',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
