# Generated by Django 2.1 on 2020-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('app', '0003_auto_20200420_0739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PType',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='type',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
